# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.0.0
      hooks:
          - id: mypy
            additional_dependencies: ['types-redis','sqlalchemy-stubs']
            exclude: alembic

    - repo: https://github.com/psf/black
      rev: 23.1.0
      hooks:
          - id: black
    - repo: local
      hooks:
        - id: pylint
          name: pylint
          entry: pylint
          language: system
          types: [python]
          args:
            [
              "-rn",
              "-sn",
              "--disable=R,C",
              "--init-hook=import sys; sys.path.append('.')",
              "--ignore-paths=alembic",

            ]

    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
          - id: isort
            args: ["--profile", "black"]
