version: "3"
services:

  fastapi:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: fastapi-step
    ports:
      - "8000:8000"
    network_mode: host

  redis_db:
    image: redis:latest
    network_mode: host
    ports:
      - target: ${REDIS_PORT}
        published: ${REDIS_PORT}

  rq-default:
    image: fastapi-step
    command: rq worker ${RQ_QUEUE} --url redis://${REDIS_HOST}:${REDIS_POST}/${REDIS_DB}
    depends_on:
      - redis_db
    network_mode: host

  minio:
    image: minio/minio
    network_mode: host
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${S3_ACCESS_KEY}
    command: server --console-address ":9001" /data

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    network_mode: host
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
